#server:
#  port: 8081


spring:
  application:
    name: API-Gateway
  config:
    import: optional:configserver:http://localhost:8888
#  main:
#    web-application-type: reactive

#eureka:
#  client:
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/