spring:
  application:
    name: Administrative-Service
  data:
    mongodb:
      uri: mongodb+srv://hashanmadhuwantha2000:@educational-platform.etxrxi5.mongodb.net/Educational-Platform?retryWrites=true&w=majority&appName=Educational-Platform
      auto-index-creation: true

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
