spring:
  application:
    name: Authentication-Service
  data:
    mongodb:
      uri: mongodb+srv://hashanmadhuwantha2000:0nDyIlj8FhZQTj4H@educational-platform.etxrxi5.mongodb.net/Educational-Platform?retryWrites=true&w=majority&appName=Educational-Platform
      auto-index-creation: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/