server:
  port: 8083

spring:
  application:
    name: Course-Management-Service
  data:
    mongodb:
      uri: mongodb+srv://:@educational-platform.etxrxi5.mongodb.net/Educational-Platform?retryWrites=true&w=majority&appName=Educational-Platform
      auto-index-creation: true
  cloud:
    azure:
      storage:
        blob:
          connection-string: BlobEndpoint=https://
          container-name: course-content
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
