server:
  port: 8083

spring:
  application:
    name: Course-Management-Service
  data:
    mongodb:
      uri: mongodb+srv://hashanmadhuwantha2000:0nDyIlj8FhZQTj4H@educational-platform.etxrxi5.mongodb.net/Educational-Platform?retryWrites=true&w=majority&appName=Educational-Platform
      auto-index-creation: true
  cloud:
    azure:
      storage:
        blob:
          connection-string: BlobEndpoint=https://dsonlinelearningplatform.blob.core.windows.net/;QueueEndpoint=https://dsonlinelearningplatform.queue.core.windows.net/;FileEndpoint=https://dsonlinelearningplatform.file.core.windows.net/;TableEndpoint=https://dsonlinelearningplatform.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-05-01T01:46:20Z&st=2024-04-30T17:46:20Z&spr=https&sig=V7e6yQQltoRT0UNoVtjlEPDtVvZJpScFTB5Q8Yic6HU%3D
          container-name: course-content
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB