server:
  port: 8084

spring:
  application:
    name: stripe-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



#  config:
#    import: "optional:configserver:http://localhost:8088"